# This is a basic workflow to help you get started with Actions名称：签到

于：
  ＃推送：
    ＃个分支：[master]
  workflow_dispatch：
  时间表：
    - cron的：30 23 * *？
  观看：
    类型：开始
    
职位：
  运行：
    运行：ubuntu-latest
    名称：签到
    ＃如果：github.event.repository.owner.id == github.event.sender.id
    步骤：
        -名称：结帐代码
          用途：actions / checkout @ v2
          
        -名称：运行时间
          运行：|
           时间= $（curl -s“ http://quan.suning.com/getSysTime.do”）
           echo -e“当前时间：$（echo” $ {time}“ | awk -F'”：“ |”，'''{print $ 2}'）“
           
    ＃设置参数的值为脚本支持的参数，如githubaction会员中心13800008888 @ 112233 18388880000 @ 123456
 
        -名称：运行号码签到
          env：
           参数：$ {{secrets.PARAMETER}}
          运行：|
           bash CnUnicom.sh $ PARAMETER
